### ISSUE TITLE
[HELP] Unhandled error during execution of render function

### ISSUE THREAD

**Issue by jeffagostinho** [Jexordexan/vue-slicksort#158]
Hello guys,

I'm using the project in my application and I'm getting this error

```
[Vue warn]: Unhandled error during execution of render function 
  at <SlickList axis="y" value= []length: 0[[Prototype]]: Array(0) tag=
```

My implementation looks like this

```
<slick-list axis="y" value="prizes" tag="ul"
            class="flex flex-col divide divide-y  w-full"
            @input="sortUpdated">
```

This implementation of mine is old and I updated the package today. I'm using vue 3

If anyone can help me I would be very grateful

Hugs

**Comment by jeffagostinho** [comment]
Error

```
app.js:67935 Uncaught (in promise) TypeError: h is not a function
    at Proxy.render (app.js:67935:14)
    at renderComponentRoot (app.js:9981:44)
    at ReactiveEffect.componentUpdateFn [as fn] (app.js:14098:57)
    at ReactiveEffect.run (app.js:7918:25)
    at setupRenderEffect (app.js:14224:9)
    at mountComponent (app.js:14007:9)
    at processComponent (app.js:13965:17)
    at patch (app.js:13566:21)
    at mountChildren (app.js:13753:13)
    at mountElement (app.js:13662:17)
```

**Comment by jeffagostinho** [comment]
I looked at the correct documentation and it worked ^^

**Comment by cuipanfengcool** [comment]
> I looked at the correct documentation and it worked ^^
I also encountered the same problem. How did you solve it

**Comment by jeffagostinho** [comment]
@cuipanfengcool for vue 3 version see here https://vue-slicksort.netlify.app/

**This is my current code which is working perfectly**

```
<slick-list axis="y" :value="prizes" :list="prizes" tag="ul" v-model:list="prizes" @update:list="sortUpdated">
    <slick-item v-for="(prize, index) in prizes" :index="index" :key="prize" tag="li">
    ...
...
```

**Comment by cuipanfengcool** [comment]
@jeffagostinho thx  it worked
